/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/invoices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invoices/{businessKey}/issuances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["issue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invoices/{businessKey}/corrections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["correct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/records/{recordId}/verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["verify"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invoices/{businessKey}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invoices/{businessKey}/renderings/xrechnung": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["renderXRechnung"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chains/{chainId}/verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["verify_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subjects/{subjectId}/personal-data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["suppress"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BuyerDto: {
            name: string;
            taxIdentifier?: string;
            countryCode: string;
            address?: string;
            email?: string;
            phone?: string;
        };
        InvoiceLineDto: {
            lineIdentifier: string;
            itemName: string;
            quantity: number;
            unitCode: string;
            unitPrice: number;
            lineDiscount?: number;
            taxCategory: string;
            taxRate: number;
            vatExemptionReason?: string;
        };
        InvoiceRequestDto: {
            saleId: string;
            issuer: components["schemas"]["IssuerDto"];
            buyer: components["schemas"]["BuyerDto"];
            currency: string;
            /** Format: date */
            issueDate: string;
            lines: components["schemas"]["InvoiceLineDto"][];
            documentLevelAllowance?: number;
        };
        IssuerDto: {
            name: string;
            taxIdentifier: string;
            countryCode: string;
        };
        InvoiceResponseDto: {
            businessKey?: string;
            state?: string;
            issuerTaxIdentifier?: string;
            buyerName?: string;
            currency?: string;
            /** Format: date */
            issueDate?: string;
            taxExclusiveAmount?: number;
            taxTotal?: number;
            taxInclusiveAmount?: number;
        };
        CorrectionRequestDto: {
            reason: string;
        };
        RecordVerificationView: {
            /** Format: uuid */
            recordId?: string;
            hash?: string;
            previousHash?: string;
            /** Format: int64 */
            chainPosition?: number;
            /** Format: date-time */
            issuedAt?: string;
            nonSubmittedNotice?: string;
        };
        ChainVerificationView: {
            status?: string;
            /** Format: int64 */
            recordsVerified?: number;
            /** Format: uuid */
            brokenRecordId?: string;
            storedHash?: string;
            recomputedHash?: string;
            /** Format: int64 */
            totalMismatches?: number;
        };
        PersonalDataSuppressionRequestDto: {
            justification: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvoiceRequestDto"];
            };
        };
        responses: {
            /** @description Registered in DRAFT. Idempotent: re-registering the same businessKey returns the existing draft. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["InvoiceResponseDto"];
                };
            };
            /** @description Already registered in a different state */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description EN 16931 validation violations */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    issue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                businessKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Issued; body carries the regime-resolved state */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["InvoiceResponseDto"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid state for issuance */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Regime unreachable — document left in NEEDS_RECONCILIATION, never retried blindly (ADR-003) */
            424: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["InvoiceResponseDto"];
                };
            };
        };
    };
    correct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                businessKey: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CorrectionRequestDto"];
            };
        };
        responses: {
            /** @description Correcting document created (RF-004: never an edit) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid state, or the regime refused the correction */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    verify: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recordId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RecordVerificationView"];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                businessKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["InvoiceResponseDto"];
                };
            };
            /** @description No invoice with that businessKey */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    renderXRechnung: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                businessKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description EN 16931 / XRechnung CII document */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/xml": string;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Mapping constraint violated — never a silently invalid document */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    verify_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chainId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description INTACT with recordsVerified, or BROKEN with brokenRecordId, storedHash, recomputedHash, totalMismatches and recordsVerified */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ChainVerificationView"];
                };
            };
            /** @description Unknown chain, or a chain with zero records — indistinguishable, so answered honestly as not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    suppress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subjectId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonalDataSuppressionRequestDto"];
            };
        };
        responses: {
            /** @description Idempotent: SUPPRESSED, or ALREADY_SUPPRESSED if the key was already destroyed (RF-007) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description Any role other than ADMIN — issuance and evidence destruction never share an identity (CV-08) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description An active fiscal retention obligation still covers this subject */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
