#!/usr/bin/env bash
# T-906: writes the .env docker-compose.prod.yml reads, and mints the two demo tokens the
# frontend build embeds. Deliberately reuses scripts/demo/generate-keypair.sh and
# scripts/demo/mint-token.sh rather than reimplementing key generation and JWT signing a second
# time — those are already built and tested (T-705).
#
# Run this ON THE SERVER, after cloning the repo, before the first `docker compose -f
# docker-compose.prod.yml up --build`. Re-running it rotates the keypair and every previously
# issued token stops verifying immediately — this is also what deploy/reset.sh calls on its
# schedule (docs/deployment.md).
#
# Usage: deploy/setup-prod-env.sh <domain>
#   <domain>  the real domain (or an sslip.io/nip.io name — see docs/deployment.md) Caddy will
#             request a Let's Encrypt certificate for. Required: nothing safe to default to here.
set -euo pipefail
cd "$(dirname "$0")/.."

DOMAIN="${1:?usage: deploy/setup-prod-env.sh <domain>}"
CADDY_STATIC_IP="172.28.0.10" # must match docker-compose.prod.yml's edge network

rm -rf .demo
./scripts/demo/generate-keypair.sh

PUBLIC_KEY_ONE_LINE=$(tr -d '\n' < .demo/public.pem)
DB_PASSWORD=$(openssl rand -hex 24)
TOKEN_TTL_SECONDS=$((48 * 3600)) # covers this run until the next scheduled reset (docs/deployment.md)

OPERATOR_TOKEN=$(./scripts/demo/mint-token.sh "operator:demo" "OPERATOR" "$TOKEN_TTL_SECONDS")
AUDITOR_TOKEN=$(./scripts/demo/mint-token.sh "auditor:demo" "AUDITOR" "$TOKEN_TTL_SECONDS")
# Deliberately no ADMIN token — see ADR-010 and RateLimitFilter's own comment on why a public
# build must never carry one.

cat > .env <<EOF
# Generated by deploy/setup-prod-env.sh. Rotates on every run; never committed (.gitignore).
POSTGRES_DB=tributary
POSTGRES_USER=tributary_owner
POSTGRES_PASSWORD=${DB_PASSWORD}
TRIBUTARY_DB_URL=jdbc:postgresql://postgres:5432/tributary
TRIBUTARY_DB_USERNAME=tributary_owner
TRIBUTARY_DB_PASSWORD=${DB_PASSWORD}
TRIBUTARY_JWT_PUBLIC_KEY=${PUBLIC_KEY_ONE_LINE}
# Caddy forwards the client's real Host header unchanged (its default reverse_proxy behaviour) —
# this must be the same domain Caddy requests a certificate for, below.
TRIBUTARY_ALLOWED_HOSTS=${DOMAIN}
TRIBUTARY_TRUSTED_PROXIES=${CADDY_STATIC_IP}
TRIBUTARY_DOMAIN=${DOMAIN}
VITE_DEMO_TOKEN_OPERATOR=${OPERATOR_TOKEN}
VITE_DEMO_TOKEN_AUDITOR=${AUDITOR_TOKEN}
EOF

echo "Wrote .env for ${DOMAIN}. Demo tokens valid for $((TOKEN_TTL_SECONDS / 3600))h, no ADMIN token minted."
echo "Next: docker compose -f docker-compose.prod.yml up --build -d"
