#!/usr/bin/env bash
# T-705: one-shot setup for the docker-compose demo — generates a throwaway JWT keypair, writes
# the .env file docker-compose reads, and mints three demo tokens (one per role) so a reviewer
# can exercise every endpoint in the SRS's own endpoint table without standing up a real
# authorization server. Safe to re-run: reuses an existing keypair instead of rotating it under
# already-minted tokens.
#
# Profiles (ADR-010):
#   default        public-demo shape — mints OPERATOR and AUDITOR only. No ADMIN token is created,
#                  so `DELETE /subjects/{id}/personal-data` is unreachable: tokens are RS256-signed
#                  and minting one requires the private key, which never ships. That is a
#                  cryptographic guarantee, not a UI guard.
#   --with-admin   local-only full demo, including ADMIN. Never use for a public deployment.
set -euo pipefail
cd "$(dirname "$0")/../.."

WITH_ADMIN=false
[ "${1:-}" = "--with-admin" ] && WITH_ADMIN=true

./scripts/demo/generate-keypair.sh

PUBLIC_KEY_ONE_LINE=$(tr -d '\n' < .demo/public.pem)
DB_PASSWORD=$(openssl rand -hex 24)
WEB_ORIGIN="${TRIBUTARY_WEB_ORIGIN:-http://localhost:5173}"

cat > .env <<EOF
# Generated by scripts/demo/setup.sh — a fresh keypair and a random local-only DB password,
# never a real credential. Gitignored; regenerate any time with this script.
TRIBUTARY_DB_URL=jdbc:postgresql://postgres:5432/tributary
TRIBUTARY_DB_USERNAME=tributary_owner
TRIBUTARY_DB_PASSWORD=${DB_PASSWORD}
TRIBUTARY_JWT_PUBLIC_KEY=${PUBLIC_KEY_ONE_LINE}
TRIBUTARY_ALLOWED_HOSTS=localhost
# ADR-010: the CORS allowlist stops being theoretical — one browser origin now exists. Still an
# explicit allowlist, never a wildcard (SRS 5.3).
TRIBUTARY_CORS_ALLOWED_ORIGINS=${WEB_ORIGIN}
TRIBUTARY_REGIME=ES
TRIBUTARY_SERVER_PORT=8080
POSTGRES_DB=tributary
POSTGRES_USER=tributary_owner
POSTGRES_PASSWORD=${DB_PASSWORD}
EOF

OPERATOR_TOKEN=$(./scripts/demo/mint-token.sh "operator:demo" "OPERATOR" 86400)
AUDITOR_TOKEN=$(./scripts/demo/mint-token.sh "auditor:demo" "AUDITOR" 86400)

cat > .demo/tokens.txt <<EOF
OPERATOR_TOKEN=${OPERATOR_TOKEN}
AUDITOR_TOKEN=${AUDITOR_TOKEN}
EOF

# Frontend build-time credentials. Deliberately WITHOUT an ADMIN token unless --with-admin: see
# the profile note at the top of this file and AdminPanel.tsx.
cat > tributary-web/.env.local <<EOF
VITE_API_BASE_URL=http://localhost:8080
VITE_DEMO_TOKEN_OPERATOR=${OPERATOR_TOKEN}
VITE_DEMO_TOKEN_AUDITOR=${AUDITOR_TOKEN}
EOF

if [ "$WITH_ADMIN" = true ]; then
  ADMIN_TOKEN=$(./scripts/demo/mint-token.sh "admin:demo" "ADMIN" 86400)
  echo "ADMIN_TOKEN=${ADMIN_TOKEN}" >> .demo/tokens.txt
  echo "VITE_DEMO_TOKEN_ADMIN=${ADMIN_TOKEN}" >> tributary-web/.env.local
  echo "NOTE: minted an ADMIN token (--with-admin). Local use only — never deploy this build."
fi

cat <<EOF
Demo environment ready.

  1. docker compose up --build

  2. In another shell, source the demo tokens (valid 24h):
       source .demo/tokens.txt

  3. Register and issue an invoice as OPERATOR:
       curl -s -X POST http://localhost:8080/api/v1/invoices \\
         -H "Authorization: Bearer \$OPERATOR_TOKEN" -H "Content-Type: application/json" \\
         -H "Host: localhost" -d @scripts/demo/sample-invoice.json

See README.md for the full walkthrough (all 8 endpoints, one per role).
EOF
